# Generated by Django 3.1.7 on 2021-03-04 23:44

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='djangoclasses',
            name='course_number',
            field=models.IntegerField(blank=True, default='', validators=[django.core.validators.MaxValueValidator(999)]),
        ),
        migrations.AlterField(
            model_name='djangoclasses',
            name='duration',
            field=models.DurationField(),
        ),
    ]
