# Generated by Django 3.1.7 on 2021-03-13 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0011_auto_20210312_1842'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Type',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit')], max_length=60),
        ),
    ]
