# Generated by Django 3.1.7 on 2021-03-13 03:00

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0012_auto_20210312_1958'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='transaction',
            managers=[
                ('Transactions', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterField(
            model_name='transaction',
            name='Type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], max_length=60),
        ),
    ]
