# Generated by Django 3.1.7 on 2021-03-16 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0015_auto_20210315_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='transaction',
            name='Type',
            field=models.CharField(choices=[('Withdrawal', 'Withdrawal'), ('Deposit', 'Deposit')], max_length=60),
        ),
    ]
