# Generated by Django 3.1.6 on 2021-03-17 01:54

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('Transactions', '0017_auto_20210315_2037'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='account',
            managers=[
                ('Accounts', django.db.models.manager.Manager()),
            ],
        ),
        migrations.RenameField(
            model_name='account',
            old_name='First_Name',
            new_name='first_name',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Starting_Balance',
            new_name='initial_deposit',
        ),
        migrations.RenameField(
            model_name='account',
            old_name='Last_Name',
            new_name='last_name',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Account',
            new_name='account',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Amount',
            new_name='amount',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Date_of_Transaction',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='transaction',
            old_name='Description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='Type',
        ),
        migrations.AddField(
            model_name='transaction',
            name='type',
            field=models.CharField(choices=[('Deposit', 'Deposit'), ('Withdrawal', 'Withdrawal')], default='', max_length=60),
        ),
    ]
